### PR TITLE
Update Visual Studio projects

### PR DESCRIPTION
**Pull request by tandasat**
This patch fixes multiple issues with Visual Studio projects. Issues and fixes are as follows (order of commits):

- Do not maintain them as a zip file, as it is not reviewable when someone wants to introduce a change. Extracted the contents. 
- [MSB8012](https://docs.microsoft.com/en-us/visualstudio/msbuild/errors/msb8012?view=vs-2022) warnings. Adjusted project settings. 
- It does not compile when `--enable-avx` is specified. Added missing files and specified a dependency on `avx` in the `cpu` project.
- A reference to a non-existent project `disasm`. Removed it. 
- The solution file version being `Visual Studio Express 2013`. I let VS2019 auto update the .sln file.

Reviewing commit-by-commit is recommended.

The last commit enables `--enable-avx` . The intent is "not to reintroduce the same issue" and "enabling more pre-defined CPUs options is better" mentality, but it may be controversial. I do not fully understand trade off (downside) of enabling this, and perfectly fine to take out that commit, as appropriate. 

Note that the same, documented build steps (`sh .conf.win32-vcpp && make win32_snap` , then open `vs2019\bochs.sln` on VS) remain to work. Confirmed that the structure (ie, contents) of `bochs-msvc-src.zip` did not change before and after this patch.

### CODE REVIEW

**Comment by therealdreg** [comment]
Hey @tandasat  I had some issues following these steps:

sh .conf.win64-vcpp 

Open .sln and try to compile as x64 executable

Can you compile as x64 project in your machine using VS2019? (with 32 bit version works fine)

**Comment by tandasat** [comment]
@therealdreg `.conf.win64-vcpp` is not working for me either. I did not attempt to resolve that in this PR.

**Comment by tandasat** [comment]
I received notification saying `[bochs-emu/Bochs] Run failed at startup: C/C++ CI - update-vs-projects (016c058)` with a link to https://github.com/bochs-emu/Bochs/actions/runs/2937745936.

Not familiar with this but the settings appear to be broken.

**Review by stlintel — DISMISSED** [review]

**Comment by stlintel** [comment]
I suggest to add --enable-avx to .conf.win64-vcpp too

**Comment by stlintel** [comment]
> Hey @tandasat I had some issues following these steps:
> 
> sh .conf.win64-vcpp
> 
> Open .sln with VS2019
> 
> Try to compile with x64 version
> 
> Can you compile it as x64 project in your machine using VS2019? (with 32 bit version works fine)

What is the error ? What does not compile ?

**Comment by stlintel** [comment]
> Not familiar with this but the settings appear to be broken.

I have fixed the settings, now CI/DI is running at least for me
Once Visual Studio build is stable need to confider having CI/DI with Visual Studio target as well

**Comment by tandasat** [comment]
`1488975dabb8fba0db6bd09151ce9ff1519bfd5a` adds enable-avx to `bochs\.conf.win64-vcpp` too.

**Comment by tandasat** [comment]
Re: x64 windows build. I filed the issue https://github.com/bochs-emu/Bochs/issues/8.

**Review by stlintel — APPROVED** [review]

**Pull request merged**
