### PR TITLE
port GUI page table dump routine from text debugger to GUI debugger code

### PR DESCRIPTION
**Pull request by stlintel**
it is copy-paste but I didn't find a way to do it better yet

supposed to help with https://github.com/bochs-emu/Bochs/issues/393

### CODE REVIEW

**Comment by Vort** [comment]
1. [I checked and confirmed that LineCount < 1024 is the cause.](https://github.com/bochs-emu/Bochs/issues/393#issuecomment-2495482218) [Your code still contains this check.](https://github.com/bochs-emu/Bochs/blob/335cb11078165d136afef2767114c7c5a1a13b86/bochs/gui/enh_dbg.cc#L1650) So problem from #393 remains in place.
2. `bool valid;` is missing.

**Comment by stlintel** [comment]
Without Line <= 1024 it might print too many pages and printing too many pages might take too much time.
Is it safe to let him traversal entire page table which might contains hundreds of thousands pages in worst case ?

**Comment by stlintel** [comment]
Make it 10000 would be good for your most of the needs, what do you say ?

**Comment by Vort** [comment]
> Make it 10000 would be good for your most of the needs, what do you say ?

Ok.

Proper solution is to split page table into... pages.
But that's a task for another time.

**Pull request merged**
